### ISSUE TITLE
Add <Evolution Land>

### ISSUE THREAD

**Issue by Evolution-Land** [Baelyk/renegade-map#16]
Hey i LORD EMPEROR WHALE LORD wish that there will be some oil on those lovely islands up north <3
-Whale lord

P.S 
That lake is made out of liquide trash :O
![inkedpolitical map renegade_li](https://user-images.githubusercontent.com/32577503/31288957-53bfbe6e-aac7-11e7-9730-b4c4f7744a97.jpg)

p.p.s this map is much cooler is the first version you made congrats to you my friend baby 👍

**Comment by Baelyk** [comment]
That size is fine. Also, Timothia made the map design, I just maintain it.

**Comment by Baelyk** [comment]
That top left island is another nation (Pensyltuckee Island), so I will leave that out.

**Comment by Baelyk** [comment]
Added
